### ISSUE TITLE
Have error when use flash.bat

### ISSUE THREAD

**Issue by MelioraHS** [volca/keylogger-pio#1]
Tool Manager: Installing framework-arduinoespressif32 @ ~2.10003.190916
Error: Could not find the package with 'framework-arduinoespressif32 @ ~2.10003.190916' requirements for your system 'windows_amd64'
I have this error on linux and on windwos the same, and cant write my firmware help please

**Comment by volca** [comment]
Could you please provide more log for `flash.bat`?

**Comment by MelioraHS** [comment]
For all guys who stuck with same problem

Need cd to keylogger-pio/esp32/platformio.ini
Change platform to espressif32@6.1.0
Delete line 35 and 36 then save file.
2 Days of Hell is over thank you mr creater for not responcing

**Comment by volca** [comment]
Thanks for update. I've changed the file.
